# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mockrolebind
  namespace: mockspace
subjects:
- kind: ServiceAccount
  name: mock-sa                # must match the service account name
  namespace: mockspace

roleRef:
  kind: Role
  name: mock-role
  apiGroup: rbac.authorization.k8s.io
---
