apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
    {{- with .Values.secret.data }}
    {{- toYaml . | nindent 2 }}
    {{- end }}